/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CamadaView;

import CamadaDAO.Conexao_banco;
import CamadaDAO.Conexao_post;
import CamadaDTO.Post;
import CamadaDTO.usuarioLogado;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSetMetaData;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author will
 */
public class postagemView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(postagemView.class.getName());

    private DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yy | HH:mm:ss");

    Connection conexao = null;
    ResultSetMetaData rs = null;

    /**
     * Creates new form NewJFrame
     */
    public postagemView() {
        initComponents();

        Timer timer = new Timer(1000, e -> atualizarHora());
        timer.start();

        atualizarHora();

        // Conectar ao banco
        conexao = Conexao_banco.conector();
        System.out.println(conexao);

        // Define o ícone conforme a conexão
        if (conexao != null) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Conexao_boa.png"));
            Image img = icon.getImage().getScaledInstance(Icone2.getWidth(), Icone2.getHeight(), Image.SCALE_SMOOTH);
            Icone2.setIcon(new ImageIcon(img));
            Icone2.setText("");

            conexaotxt2.setText("Banco ON");
            conexaotxt2.setForeground(Color.green);
        } else {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens.Conexao_perdida.png"));
            Image img = icon.getImage().getScaledInstance(Icone2.getWidth(), Icone2.getHeight(), Image.SCALE_SMOOTH);
            Icone2.setIcon(new ImageIcon(img));
            Icone2.setText("");

            conexaotxt2.setText("Banco OFF");
            conexaotxt2.setForeground(Color.red);
        }

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/background.jpg"));
        Image img = icon.getImage().getScaledInstance(fundo2.getWidth(), fundo2.getHeight(), Image.SCALE_SMOOTH);
        fundo2.setIcon(new ImageIcon(img));
        fundo2.setText("");

        Autor.setText(usuarioLogado.getUsuario().getUsuario());
    }

    private void atualizarHora() {
        LocalDateTime agora = LocalDateTime.now();
        Tempo.setText(agora.format(formato));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OM1 = new javax.swing.JMenu();
        SOP1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        OM3 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensagem = new javax.swing.JTextArea();
        Autor = new javax.swing.JTextField();
        Postar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Tempo = new javax.swing.JLabel();
        conexaotxt2 = new javax.swing.JLabel();
        Icone2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        troca = new javax.swing.JToggleButton();
        fundo2 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        OM2 = new javax.swing.JMenu();
        SOP2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        OM4 = new javax.swing.JMenu();
        exit1 = new javax.swing.JMenuItem();

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        OM1.setText("Postagens");

        SOP1.setText("Criar post");
        SOP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOP1ActionPerformed(evt);
            }
        });
        OM1.add(SOP1);

        jMenuBar1.add(OM1);

        jMenu2.setText("Perfil");

        jMenuItem2.setText("Ver perfil");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Editar perfil");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        OM3.setText("Configurações");

        exit.setText("Sair");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        OM3.add(exit);

        jMenuBar1.add(OM3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mensagem.setBackground(new java.awt.Color(51, 51, 51));
        Mensagem.setColumns(20);
        Mensagem.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        Mensagem.setForeground(new java.awt.Color(255, 255, 255));
        Mensagem.setRows(5);
        jScrollPane1.setViewportView(Mensagem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 400, 200));

        Autor.setBackground(new java.awt.Color(51, 51, 51));
        Autor.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        Autor.setForeground(new java.awt.Color(255, 255, 255));
        Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorActionPerformed(evt);
            }
        });
        getContentPane().add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 280, 34));

        Postar.setBackground(new java.awt.Color(51, 51, 51));
        Postar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Postar.setForeground(new java.awt.Color(255, 255, 255));
        Postar.setText("Postar");
        Postar.setToolTipText("");
        Postar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Postar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostarActionPerformed(evt);
            }
        });
        getContentPane().add(Postar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 149, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tempo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Tempo.setForeground(new java.awt.Color(255, 255, 255));
        Tempo.setText("jLabel1");

        conexaotxt2.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        conexaotxt2.setText("Icone");

        Icone2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Icone2.setText("Conect");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tempo, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Icone2)
                    .addComponent(conexaotxt2))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(Icone2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conexaotxt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 130, 470));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Postagem:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensagem:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Autor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        troca.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        troca.setText("Trocar autor");
        troca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocaActionPerformed(evt);
            }
        });
        getContentPane().add(troca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 114, 110, 30));

        fundo2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        fundo2.setText("jLabel4");
        getContentPane().add(fundo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 470));

        Menu2.setBackground(new java.awt.Color(255, 255, 255));
        Menu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Menu2.setForeground(new java.awt.Color(0, 0, 0));

        jMenu3.setText("Home");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        Menu2.add(jMenu3);

        OM2.setText("Postagens");

        SOP2.setText("Criar post");
        SOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOP2ActionPerformed(evt);
            }
        });
        OM2.add(SOP2);

        Menu2.add(OM2);

        jMenu4.setText("Perfil");

        jMenuItem4.setText("Ver perfil");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Editar perfil");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        Menu2.add(jMenu4);

        OM4.setText("Configurações");

        exit1.setText("Sair");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        OM4.add(exit1);

        Menu2.add(OM4);

        setJMenuBar(Menu2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostarActionPerformed
        String autor = Autor.getText();
        String conteudo = Mensagem.getText();

        if (conteudo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Escreva uma mensagem antes de postar!");
            return;
        }

        Post post = new Post(autor, conteudo);
        Conexao_post dao = new Conexao_post();

        if (dao.cadastrar(post)) {
            Tela_principal tela = new Tela_principal();
            tela.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_PostarActionPerformed

    private void SOP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SOP1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

    }//GEN-LAST:event_exitActionPerformed

    private void SOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOP2ActionPerformed
        // TODO add your handling code here0:
        postagemView cadastro = new postagemView();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SOP2ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        if (exit1.isEnabled()) {
            CadastroView cad = new CadastroView();
            cad.setVisible(false);
            this.dispose();

            Object[] opcoes = {"Não", "Sim"};
            int escolha = JOptionPane.showOptionDialog(null, "Deseja sair?", "Saida", 0, 0, null, opcoes, opcoes[0]);

            if (escolha == 1) {
                loginView cadastro = new loginView();

                usuarioLogado.limparUsuario();

                cadastro.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "retornando...");

                Tela_principal cadastro = new Tela_principal();
                cadastro.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_exit1ActionPerformed

    private void AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorActionPerformed

    }//GEN-LAST:event_AutorActionPerformed

    private void trocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocaActionPerformed
        if (troca.isSelected()) {
            Autor.setText(usuarioLogado.getUsuario().getNome());
            Autor.setEditable(false);
        } else {
            Autor.setText(usuarioLogado.getUsuario().getUsuario());
            Autor.setEditable(false);
        }
    }//GEN-LAST:event_trocaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Tela_principal cadastro = new Tela_principal();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ImageIcon user = new ImageIcon(getClass().getResource("/Imagens/User.png"));
        
        Object[] opcoes = {"fechar"};
        int escolha = JOptionPane.showOptionDialog(null, "Id: " + usuarioLogado.getIdAtual().getId() + "\nNome: " + usuarioLogado.getNome().getNome() + "\nUsuario: " + usuarioLogado.getUsuario().getUsuario(), "Perfil", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, user, opcoes, opcoes[0]);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        perfilView cadastro = new perfilView();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new postagemView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Autor;
    private javax.swing.JLabel Icone2;
    private javax.swing.JTextArea Mensagem;
    private javax.swing.JMenuBar Menu2;
    private javax.swing.JMenu OM1;
    private javax.swing.JMenu OM2;
    private javax.swing.JMenu OM3;
    private javax.swing.JMenu OM4;
    private javax.swing.JButton Postar;
    private javax.swing.JMenuItem SOP1;
    private javax.swing.JMenuItem SOP2;
    private javax.swing.JLabel Tempo;
    private javax.swing.JLabel conexaotxt2;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem exit1;
    private javax.swing.JLabel fundo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton troca;
    // End of variables declaration//GEN-END:variables
}
